feat: Add medium and Discourse links to Across.to
across-protocol/frontend-v1 pull request #159
Opened 2022-02-09 21:41 UTC by Tulun

Story details: https://app.shortcut.com/uma-project/story/4346

Note: Missing urls, this is for design QA once I get those.
<img width="1983" alt="Screen Shot 2022-02-09 at 1 40 12 PM" src="https://user-images.githubusercontent.com/12792146/153294757-e6a42940-41b5-467d-9f6f-ffd198b62f66.png">

2022-02-10 01:21 UTC, daywiss commented on src/components/Layout/Layout.tsx
> +    url: "",
i guess we are waiting for the links

2022-02-10 02:58 UTC, Tulun commented on src/components/Layout/Layout.tsx
> +    url: "",
Yeah asked Tom for them but wanted the PR open for design QA (as this is a trivial change)

2022-02-16 14:44 UTC, Tommy1231232 requested changes
Feedback from Jesper:
<img width="1182" alt="Screen Shot 2022-02-16 at 7 43 51 AM" src="https://user-images.githubusercontent.com/71620056/154288615-88f13b1f-61fd-475c-98fe-bc39633658b7.png">

2022-02-18 00:17 UTC, daywiss approved these changes
lgtm, can probably get rid of some of the commented out props

2022-02-18 21:08 UTC, Tommy1231232 requested changes
@Tulun colors need to be updated to match designs: 

<img width="878" alt="Screen Shot 2022-02-18 at 2 00 41 PM" src="https://user-images.githubusercontent.com/71620056/154761366-62f61eb9-262a-4319-b996-ab04cbf928ef.png">

2022-02-18 21:13 UTC, Tulun commented
> @Tulun colors need to be updated to match designs:
> 
> <img alt="Screen Shot 2022-02-18 at 2 00 41 PM" width="878" src="https://user-images.githubusercontent.com/71620056/154761366-62f61eb9-262a-4319-b996-ab04cbf928ef.png">

Can you confirm with Jesper? these are the svg logos he sent me. I need either new ones for the old icons or the new ones. Thanks.

2022-02-25 22:17 UTC, Tommy1231232 commented
@Tulun - the format of the input fields is shifted from the tabs at the top. They should be aligned. The icons at the botton still seem too light as well but will have Jesper comment on them as he knows better. 


<img width="1277" alt="Screen Shot 2022-02-25 at 5 14 41 PM" src="https://user-images.githubusercontent.com/71620056/155810423-6053096e-19ab-4627-82a7-a56aec85dd53.png">

2022-03-07 16:12 UTC, Tommy1231232 approved these changes

2022-03-07 16:12 UTC, merged